// logos.js — chemins locaux des 30 équipes NBA (format abréviation BallDontLie)
export const NBA_LOGOS = {
  ATL: './logos/atl.svg',
  BOS: './logos/bos.svg',
  BKN: './logos/bkn.svg',
  CHA: './logos/cha.svg',
  CHI: './logos/chi.svg',
  CLE: './logos/cle.svg',
  DAL: './logos/dal.svg',
  DEN: './logos/den.svg',
  DET: './logos/det.svg',
  GSW: './logos/gsw.svg',
  HOU: './logos/hou.svg',
  IND: './logos/ind.svg',
  LAC: './logos/lac.svg',
  LAL: './logos/lal.svg',
  MEM: './logos/mem.svg',
  MIA: './logos/mia.svg',
  MIL: './logos/mil.svg',
  MIN: './logos/min.svg',
  NOP: './logos/nop.svg',
  NYK: './logos/nyk.svg',
  OKC: './logos/okc.svg',
  ORL: './logos/orl.svg',
  PHI: './logos/phi.svg',
  PHX: './logos/phx.svg',
  POR: './logos/por.svg',
  SAC: './logos/sac.svg',
  SAS: './logos/sas.svg',
  TOR: './logos/tor.svg',
  UTA: './logos/uta.svg',
  WAS: './logos/was.svg'
};
